### ISSUE TITLE
Singular Matrix Error

### ISSUE THREAD

**Issue by frehburg** [raphaelreme/tps#1]
I tried to use your package with the following code but got a Singular Matrix error:

```x = np.linspace(0,20,100)
xtest = np.linspace(0,20,1000)
xtest = np.setdiff1d(np.linspace(-10,10,1000),x)
y = np.sin(1/3*x + 3) * x + np.sin(1/12*x + 1.5)
ytest = np.sin(1/3*xtest + 3) * xtest + np.sin(1/12*xtest + 1.5)

tps = ThinPlateSpline(0.5)
tps.fit(x,y)
y_pred = tps.transform(x)
ytest_pred = tps.transform(xtest)

# plot y in green, y_pred in red over x
plt.plot(x,y,'g',xtest,y_pred,'r')
plt.show()

But got this error: 

LinAlgError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18300\1389154735.py in <module>
      6 
      7 tps = ThinPlateSpline(0.5)
----> 8 tps.fit(x,y)
      9 y_pred = tps.transform(xtest)
     10 ytest_pred = tps.transform(xtest)

~\anaconda3\lib\site-packages\tps\thin_plate_spline.py in fit(self, X, Y)
     87         Y = np.vstack([Y, np.zeros((d_s + 1, Y.shape[1]))])
     88 
---> 89         self.parameters = np.linalg.solve(A, Y)
     90         self._fitted = True
     91 

<__array_function__ internals> in solve(*args, **kwargs)

~\anaconda3\lib\site-packages\numpy\linalg\linalg.py in solve(a, b)
    391     signature = 'DD->D' if isComplexType(t) else 'dd->d'
    392     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 393     r = gufunc(a, b, signature=signature, extobj=extobj)
    394 
    395     return wrap(r.astype(result_t, copy=False))

~\anaconda3\lib\site-packages\numpy\linalg\linalg.py in _raise_linalgerror_singular(err, flag)
     86 
     87 def _raise_linalgerror_singular(err, flag):
---> 88     raise LinAlgError("Singular matrix")
     89 
     90 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix

**Comment by frehburg** [comment]
I updated the code by changing `tps.fit(x,y)` to `tps.fit(x[:,np.newaxis],y[:,np.newaxis])`, but now i am getting this error: 

```
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18300\1567068639.py in <module>
      7 tps = ThinPlateSpline(0.5)
      8 tps.fit(x[:,np.newaxis],y[:,np.newaxis])
----> 9 y_pred = tps.transform(x)
     10 ytest_pred = tps.transform(xtest)
     11 

~\anaconda3\lib\site-packages\tps\thin_plate_spline.py in transform(self, X)
    106 
    107         X = _ensure_2d(X)
--> 108         assert X.shape[1] == self.control_points.shape[1]
    109 
    110         phi = self._radial_distance(X)  # n x n_c

AssertionError:
```

**Comment by frehburg** [comment]
Could you please provide me with a very short tutorial on how to use your package? I am trying to use it on 4 dimensional data where 3d (x,y,z) is space and t is the variable i would like to interpolate. For this i have points in 3d space that are not contained in my original data and want to compute their interpolated t values. How can i achieve this? (In the code above i was just trying to get used to your package)

**Comment by raphaelreme** [comment]
> I updated the code by changing `tps.fit(x,y)` to `tps.fit(x[:,np.newaxis],y[:,np.newaxis])`, but now i am getting this error:
> 
> ```
> AssertionError                            Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_18300\1567068639.py in <module>
>       7 tps = ThinPlateSpline(0.5)
>       8 tps.fit(x[:,np.newaxis],y[:,np.newaxis])
> ----> 9 y_pred = tps.transform(x)
>      10 ytest_pred = tps.transform(xtest)
>      11 
> 
> ~\anaconda3\lib\site-packages\tps\thin_plate_spline.py in transform(self, X)
>     106 
>     107         X = _ensure_2d(X)
> --> 108         assert X.shape[1] == self.control_points.shape[1]
>     109 
>     110         phi = self._radial_distance(X)  # n x n_c
> 
> AssertionError:
> ```

Hi !

Indeed you need to give the tps object 2 dimensionals arrays.
With your current code you also need to expand dims when calling transform:

```python
tps.fit(x[:, None], y[:, None])
y_pred = tps.transform(x[:, None])
ytest_pred = tps.transform(xtest[:, None])
```

I think I will add/correct the automatic conversion of 1d array in a future version so that your code which is intuitive works.

**Comment by raphaelreme** [comment]
For your multidimensional case, here is how it should work:

```python
alpha = ...
data = ... # Shape (N, 4) (N control points. Each control point is (x, y, z, t))
space = data[:, :3]  # Shape (N, 3)
time = data[:, 3:]  # Shape (N, 1)

tps = ThinPlateSpline(alpha)
tps.fit(space, time)  # Learns a mapping from space to time

new_space = ... # Shape (M, 3) -> New (x, y, z) for which you want to extrapolate t.
new_t = tps.transform(new_space)
```

Let me know if it helps and if you are still facing issues

**Comment by frehburg** [comment]
Thank you, the 2D case works. How can i find out about the error of the interpolation? Is there a way to increase its accuracy?

**Comment by raphaelreme** [comment]
Nice to hear!

If you have the ground truth you can simply measure the error by computing the MSE or MAE ? You can also look in scikit-learn if they define better metrics for interpolation.

You can play with is alpha, the regularization parameter. For instance, try a grid search (or even visually try several ones and see which works the best for you). It should interpolate smoothly between the control points you give. But if you try to predict outside of the domain of your control points, it will only propagate the smoothness from the closest control points, so it is usually better if your control points are spread all around the space you want to interpolate.

**Comment by raphaelreme** [comment]
> I think I will add/correct the automatic conversion of 1d array in a future version so that your code which is intuitive works.

Done with commit 7d6762f. With the new version (pip install -u thin-plate-spline -> v1.1.0), it handles more intuitively 1d array.
