### ISSUE TITLE
3D TPS

### ISSUE THREAD

**Issue by Koushouu** [raphaelreme/tps#3]
Hi Raphael,

Thanks for sharing this! From my understanding, the code right now only works for 1D and 2D signals.
I wonder are you thinking about extending it to 3D/ n-dimensions? 
Thanks.

Kou

**Comment by raphaelreme** [comment]
Hi @Koushouu 

The code should already work with n-d signals. In fact if you look at the main class documentation, you can map a $d_s$ dimensional source space into $d_t$ dimensional target space where $d_s$ and $d_t$ can be any positive integer. There is an example of this in `example/example.py` where we map a 3d space into a 2d one.

Let me know if you have any other questions :)
